- name: nodejs
  ansible.builtin.import_role:
    name: common
    tasks_from: nodejs
- name: app setup
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup
- name: copy file 
  ansible.builtin.import_role:
    name: common
    tasks_from: cpy
- name: mongodb
  ansible.builtin.import_role:
    name: common
    tasks_from: mongodb
- name: get the users count
  ansible.builtin.command:  mongo --host mongodb.daws76s.online --quiet --eval 'db = db.getSiblingDB("users"); db.users.count()'
  register: user_count

# - name: print the count
#   ansible.builtin.debug:
#     msg: "product count: {{user_count}}"

- name: load user data
  ansible.builtin.command: mongo --host mongodb.daws76s.online < /app/schema/user.js
  when: user_count.stdout == "0" # keep double quotes

- name: system start & enable
  ansible.builtin.import_role:
    name: common
    tasks_from: system