- name: app setup
  ansible.builtin.import_role:
    name: common
    tasks_from: appsetup

- name: nodejs
  ansible.builtin.import_role:
    name: common
    tasks_from: nodejs
- name: mongodb
  ansible.builtin.import_role:
    name: common
    tasks_from: mongodb
- name: system
  ansible.builtin.import_role:
    name: common
    tasks_from: system

- name: get the categories count
  ansible.builtin.command:  mongo --host 172.31.22.222 --quiet --eval 'db = db.getSiblingDB("catalogue"); db.products.count()'
  register: product_count

# - name: print the count
#   ansible.builtin.debug:
#     msg: "product count: {{product_count}}"

- name: load catalogue data
  ansible.builtin.command: mongo --host 172.31.22.222 < /app/schema/catalogue.js
  when: product_count.stdout == "0" # keep double quotes